version: '3'

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=aleksis
      - POSTGRES_DB=aleksis
  memcached:
    image: memcached:latest
  app:
    build: .
    image: registry.edugit.org/aleksis/aleksis-ng:${ALEKSIS_IMAGE_TAG:-latest}
    volumes:
      - aleksis_data:/var/lib/aleksis/
    environment:
      - ALEKSIS_http__allowed_hosts="['*']"
      - ALEKSIS_caching__memcached__address=memcached:11211
      - ALEKSIS_database__host=db
      - ALEKSIS_maintenance__debug=${ALEKSIS_maintenance__debug:-false}
    depends_on:
      - db
      - memcached
  web:
    build: ./docker/nginx
    image: registry.edugit.org/aleksis/aleksis-ng/nginx:${ALEKSIS_IMAGE_TAG:-latest}
    volumes:
      - aleksis_data:/var/lib/aleksis/
    ports:
      - ${NGINX_HTTP_PORT:-8080}:80
    depends_on:
      - app

volumes:
  postgres_data:
  aleksis_data:
